# Generated by Django 5.1.4 on 2026-08-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcore_notifier', '0007_require_channel_name_and_time_windows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_type',
            field=models.CharField(choices=[('webhook', 'Webhook'), ('email', 'Email'), ('sms', 'SMS'), ('feishu_app', 'Feishu App')], db_index=True, max_length=20),
        ),
    ]
