# Generated by Django 5.1.4 on 2026-08-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentcore_notifier', '0008_alter_notificationchannel_channel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_type',
            field=models.CharField(choices=[('webhook', 'Webhook'), ('email', 'Email'), ('sms', 'SMS'), ('feishu_app', 'Feishu App'), ('wecom_bot', 'WeCom Bot')], db_index=True, max_length=20),
        ),
    ]
